import { chromium } from '@playwright/test'
import { mkdir } from 'node:fs/promises'
await mkdir('artifacts/product-build',{recursive:true})
const browser=await chromium.launch(),page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[]
page.on('pageerror',e=>errors.push(e.message))
await page.addInitScript(()=>localStorage.setItem('hooker_vamp_access_v1','1'))
await page.goto('http://127.0.0.1:4173/create')
await page.getByRole('heading',{name:'Make your first impression.'}).waitFor()
await page.getByLabel('Token name',{exact:false}).fill('Moon Milk')
await page.getByLabel('Ticker symbol',{exact:false}).fill('MILK')
await page.getByLabel('The story',{exact:false}).fill('A little lunar alchemy. A community brewing something different on Arc.')
await page.screenshot({path:'artifacts/product-build/launch-desktop.png',fullPage:true})
await page.getByRole('button',{name:'Continue',exact:false}).click()
await page.getByRole('heading',{name:'Set the opening conditions.'}).waitFor()
await page.screenshot({path:'artifacts/product-build/pool-desktop.png',fullPage:true})
await page.setViewportSize({width:390,height:844})
await page.screenshot({path:'artifacts/product-build/launch-mobile.png',fullPage:true})
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)
await page.goto('http://127.0.0.1:4173/setup')
await page.getByRole('heading',{name:'Bring the brewery on-chain.'}).waitFor()
await page.screenshot({path:'artifacts/product-build/setup-mobile.png',fullPage:true})
await page.goto('http://127.0.0.1:4173/')
await page.locator('main h1').waitFor()
console.log(JSON.stringify({errors,mobileOverflow:overflow,homeTitle:await page.locator('main h1').innerText(),api:await page.evaluate(async()=>{const r=await fetch('/api/status');const b=await r.json();return {status:r.status,treasury:b.treasury,deployed:!!b.deployment}})},null,2))
await browser.close()
